language: cpp

compiler:  
    - gcc
    - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - make
    - cmake
    - gcc-4.8
    - g++-4.8
    - clang

before_script:  
    - mkdir -p build
    - mkdir -p bin
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - cat -n src/CMakeFiles/xstd.dir/build.make

script: cmake --build build

os:
  - linux 
