libxstd: xstd::Directory Class Reference
xstd::Directory Class Reference
[std::vector] for directory entrys
#include <directory.h>
Public Member Functions
Directory ()
Directory (const string &path, bool subdir=false, bool owndir=false)
~Directory ()
void scan (const string &path, bool subdir=false, bool owndir=false)
void sort ()
void sort (bool casesensitive)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
[std::vector] for directory entrys
This is a vector to retrieve, store and sort FileName types. No slicing can occure by passing pointers of Directorys, because no additional variables are added at all.
Todo:
excludeflag for hidden files !!
maybe use a set rather than a vector, to sort entries this is needed in FileName : bool operator<(const ... & right) const {return mTestOffset > right.mTestOffset;}
Example:
Author
Fred Klaus
Constructor & Destructor Documentation
xstd::Directory::Directory () inline
xstd::Directory::Directory (const string & path, bool subdir = false, bool owndir = false)
References scan().
xstd::Directory::~Directory () inline
Member Function Documentation
void xstd::Directory::scan (const string & path, bool subdir = false, bool owndir = false)
Todo:
errorhandling !!
Todo:
cleanup
Referenced by Directory().
void xstd::Directory::sort ()
Sorts this vector by filename. If you dont need to change the default behaviour (case insensitive), use this.
Todo:
implement dirsfirst flag
void xstd::Directory::sort (bool casesensitive)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Is NOT REALLY THREADSAFE because of using a static function in FileName.
Parameters
casesensitive = Sets whether sorting is case sensitive or not.
See Also
static stk::FileName::setCaseSensitiveCompare
References xstd::FileName::setCaseSensitiveCompare().
The documentation for this class was generated from the following files:
directory.h
directory.cpp