libxstd: xstd::FileName Class Reference
xstd::FileName Class Reference
[std::string] extension for filenames
#include <filename.h>
Public Member Functions
FileName ()
FileName (const string &filename)
~FileName ()
bool operator< (const FileName &fn)
bool operator== (const FileName &fn)
string qualified () const
string base (bool ext=true) const
string path () const
string relpath () const
string ext (bool dot=true) const
void set (const string &filename)
void setBase (const string &basename, bool ext=true)
void setExt (const string &extension)
void setPath (const string &path)
bool isValid ()
bool isRelative ()
Static Public Member Functions
static void setCaseSensitiveCompare (bool csc)
Static Private Member Functions
static const char delim ()
Static Private Attributes
static bool mCaseSensitive = false
Detailed Description
[std::string] extension for filenames
This class is derived from std::string and is nothing more or less than that, with additional functions to extract parts of a filename in a cross-safe manner under consideration of the different delimiters and the Drive/Root thing of Linux and Win32. It is also possible to sort FileNames caseinsensitive (the default) in STL containers. Also, no slicing can occure by passing pointers of FileNames, because no additional variables are added at all. Just use it as an ordinary std::string.
Todo:
Drive/Root not yet considered.
Example:
Author
Fred Klaus
Constructor & Destructor Documentation
xstd::FileName::FileName () inline
xstd::FileName::FileName (const string & filename) inline
xstd::FileName::~FileName () inline
Member Function Documentation
string xstd::FileName::base (bool ext = true) const
Bug:
with ext=false may couse bad name
References delim().
static const char xstd::FileName::delim () inline static private
Referenced by base(), path(), qualified(), relpath(), setBase(), and setPath().
string xstd::FileName::ext (bool dot = true) const
bool xstd::FileName::isRelative ()
Todo:
implement me
bool xstd::FileName::isValid ()
Todo:
implement me
bool xstd::FileName::operator< (const FileName & fn)
for case sensitive or insensitive sorting
References mCaseSensitive.
bool xstd::FileName::operator== (const FileName & fn)
for case sensitive or insensitive equalization
References mCaseSensitive.
string xstd::FileName::path () const
References delim().
string xstd::FileName::qualified () const
Todo:
not yet implemented
References delim().
string xstd::FileName::relpath () const
References delim().
void xstd::FileName::set (const string & filename) inline
Todo:
used function -localtime- not threadsafe but -localtime_r- not included in MinGW !!
implement errorhandling
void xstd::FileName::setBase (const string & basename, bool ext = true)
Todo:
ext=false not yet implemented
See Also
base
References delim().
static void xstd::FileName::setCaseSensitiveCompare (bool csc) inline static
Sets wether the operator< should work case sensitive. Switches a static
private variable and is therefore NOT THREADSAFE but in most cases riskless. Asynchronus setting this vally may cause mixed sorted Filenames.
References mCaseSensitive.
Referenced by xstd::Directory::sort().
void xstd::FileName::setExt (const string & extension)
void xstd::FileName::setPath (const string & path)
References delim().
Member Data Documentation
bool xstd::FileName::mCaseSensitive = false static private
Referenced by operator<(), operator==(), and setCaseSensitiveCompare().
The documentation for this class was generated from the following files:
filename.h
filename.cpp