libxstd: xstd Namespace Reference
xstd Namespace Reference
Classes
class DateTime
Date- and Timehandling.
class Directory
[std::vector] for directory entrys
class FileInfo
Represents Fileattributes.
class FileName
[std::string] extension for filenames
class Settings
File IO and Key/Value Handling of a Settings File.
Functions
const string & toLower (string &str)
const string & toUpper (string &str)
converts a [std::string] to lower Case
Function Documentation
const string & xstd::toLower (string & str)
Referenced by xstd::Settings::getStringL(), and xstd::Settings::load().
const string & xstd::toUpper (string & str)
converts a [std::string] to lower Case
Referenced by xstd::Settings::getStringU(), and xstd::Settings::load().